name: CI Pipeline - Analisis SAST con SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarQube-analysis:
    name: Analisis de Calidad de Codigo
    runs-on: ubuntu-latest
    
    steps:
      - name: Clonacion del repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Ejecucion de Escaner SonarQube
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=mi-proyecto-gestion-sw
            -Dsonar.qualitygate.wait=true